### ISSUE TITLE
Upgrade via pip failed

### ISSUE THREAD

**Issue by rdzudzar** [1313e/CMasher#1]
I had installation of `cmasher` via: `pip install cmasher` and when I ran: `pip install --upgrade cmasher` I get the following error:
```
Installing collected packages: six, cmasher
  Found existing installation: six 1.10.0
Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
Any suggestions?

I am using Python 3.6.1 and system: OS X Yosemite Version 10.10.5

**Comment by rdzudzar** [comment]
I went around `six` and upgraded `cmasher` like this:
`pip install --upgrade cmasher --ignore-installed six
and it is working now.

**Comment by 1313e** [comment]
Hi @rdzudzar,
it looks like `six` was installed using a different method than the normal `pip` method, either with `conda` or installed manually.
The best way to solve this issue (besides ignoring it) is to uninstall six using the method it was installed with, and then install `six` again using `pip`.
You can also check if `six` was installed using `conda` and upgrade it if so, by using `conda upgrade six`.

**Comment by rdzudzar** [comment]
Yes, after `six` upgrade via `conda`, upgrade of `cmasher` does not result in error.
