### ISSUE TITLE
`view_cmap()` does not show cmap and returns: `FigureCanvasAgg is non-interactive, and thus cannot be shown`

### ISSUE THREAD

**Issue by DanielYang59** [1313e/CMasher#128]
I hope I'm not using the `view_cmap` util incorrectly, but the following simple code doesn't seems to work:
```python
import cmasher as cmr

cmr.view_cmap("cmr.fusion")
```

and returns
```bash
/home/yang/Developer/CMasher/cmasher/utils.py:1644: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
```

Tried to install `pyqt5` and `pyqt6` as suggested [here](https://discourse.matplotlib.org/t/figurecanvasagg-interactivity-problem/24042/4) which unfortunately doesn't resolve the issue. Also all dependencies are installed from `dependencies.txt`.

Thanks!

**Comment by DanielYang59** [comment]
Closing as this seems to be specific to my WSL2-Ubuntu-22.04 install, but works fine on the native Windows machine. Not sure what might be the reason.

**Comment by neutrinoceros** [comment]
This looks like a limitation in matplotlib, rather than in CMasher. Maybe escalate this to them if needed ?

**Comment by DanielYang59** [comment]
> This looks like a limitation in matplotlib, rather than in CMasher. Maybe escalate this to them if needed ?

Thanks for the quick response. I would try digging further and then open a case there. Thanks.

**Comment by DanielYang59** [comment]
@neutrinoceros After some experiments, it seems (perhaps) the backend on WSL2 is missing, and `sudo apt install python3-tk` fixed my issue.
