### ISSUE TITLE
create_cmap_overview should have a "as input" sort

### ISSUE THREAD

**Issue by endolith** [1313e/CMasher#18]
`create_cmap_overview` can take a list as input, and the list has an order already, so `sort=` should have an option for listing the colormaps in the order they were in the list.

**Comment by 1313e** [comment]
That's not a bad idea actually.
Wonder how I did not think of that.

**Comment by 1313e** [comment]
@endolith I hope you don't mind that `sort=None` is not the default, as I have the feeling that sorting alphabetically is slightly more logical than not sorting at all.

**Comment by endolith** [comment]
That's fine.  I used it here: https://github.com/endolith/bipolar-colormap/blob/master/examples/comparison.py

**Comment by 1313e** [comment]
I saw yes, and immediately realized why you asked for this feature.

**Comment by 1313e** [comment]
I think I will also add the feature tomorrow that one can set the title of the overview (or remove it altogether).

**Comment by endolith** [comment]
That would be good too.  Did you see that I rewrote the names of the colormaps so they would display alongside?  And I had to add a space after _r names because it filters those out automatically.  I don't care that much, but maybe something to think about changing.

**Comment by 1313e** [comment]
Ah, that's the reason why that works.
Yes,I had already an idea how to deal with that.

**Comment by 1313e** [comment]
@endolith Can you check ed80773 and see if that works better?

**Comment by endolith** [comment]
@1313e Yes that works well https://github.com/endolith/bipolar-colormap/commit/214883682e457fc3be349344acef87008288a619
