### ISSUE TITLE
A set of sequential colormaps that do not start with black

### ISSUE THREAD

**Issue by escherba** [1313e/CMasher#24]
**Describe the colors you would like**

**Describe the colormap type**
Sequential, perceptually uniform (or at least colorblind friendly)

**Describe any extra properties**
The specific property I would like to request is that the colormap does not start with pure black. Sometimes it is useful to have plot background set to black color. 

**Is your colormap request related to a specific application? Please describe.**
My specific application is looking at lots of parallel coordinates plots on black background---however I think that many people who use black backgrounds would appreciate a color palette that does not start with pure black.

**Additional context**
Dusk palette
![image](https://user-images.githubusercontent.com/474486/95647799-18ed4e00-0a87-11eb-9fd3-9635d95a14a6.png)

Viridis palette -- note dark purple lines in the middle between y=0.0 and y=0.2 which disappear with all CMasher palettes
![image](https://user-images.githubusercontent.com/474486/95647810-34585900-0a87-11eb-9b66-247569cb4da3.png)

**Comment by 1313e** [comment]
@escherba Thanks for the colormap request.
CMasher already has 7 colormaps that do not start in pure black, namely those that are below `voltage` in the colormap overview.
You can also convert any other colormap to one that does not start in black, by cutting off the first part using the `cmr.get_sub_cmap` function.

However, if you don't like those options, then I would like to make a colormap for you that does satisfy your conditions.
Then I do require to know what colors you want in the colormap, as there are already several colormaps that do not start in black (and thus I would have to guess what combination I don't have yet).

**Comment by escherba** [comment]
Thank you for the quick reply! I didn't really expect you to design me a color palette -- it was more of a general request ("it would be nice to have a larger or equivalent set of colormaps that do not start with pure black"). 

But cutting off the first part is a genius idea that I didn't consider, ha! With that option, I quite like "lilac":

    cmr_cmap = cm.get_cmap('cmr.lilac', 256)
    newcolors = cmr_cmap(np.linspace(0, 1, 256)[50:-20])
    newcmp = ListedColormap(newcolors)
    plotting.parallel_coordinates(study, figsize=(10, 3), cmap=newcmp)

![image](https://user-images.githubusercontent.com/474486/95663745-84bacf80-0af6-11eb-9314-c6933ba8a68e.png)

**Comment by 1313e** [comment]
> Thank you for the quick reply! I didn't really expect you to design me a color palette -- it was more of a general request ("it would be nice to have a larger or equivalent set of colormaps that do not start with pure black").

Of course I would do that. That's the point of this issue label.


> But cutting off the first part is a genius idea that I didn't consider, ha! With that option, I quite like "lilac":

CMasher actually provides you with a function to do that more easily, called `cmr.get_sub_cmap`.
So, in your case, you could write it as:
```python
import cmasher as cmr

cmap = cmr.get_sub_cmap('cmr.lilac', 0.2, 0.9)
plotting.parallel_coordinates(study, figsize=(10, 3), cmap=cmap)
```

**Comment by 1313e** [comment]
@escherba Is your request solved now, such that I can close the issue?

PS: Cutting off the first 15% of colormaps like `dusk` and `eclipse` would probably look pretty cool for like collections.
Same goes for cutting off the last 15% of `ocean` and `horizon`.
