### ISSUE TITLE
Circular cmaps?

### ISSUE THREAD

**Issue by horsto** [1313e/CMasher#27]
I love these colormaps! 
Do you have any circular (i.e. cyclic) ones planned by any chance? 
https://matplotlib.org/3.3.3/tutorials/colors/colormaps.html#cyclic

**Comment by 1313e** [comment]
@horsto Thanks for your question, I am happy you like the colormaps.
I have been thinking of making a cyclic colormap before, but their very niche application has thus far not convinced me to do it.
I have considered converting the `seasons` colormap into a cyclic colormap, but it will require some changes to my workflow and the colormap to do so.
Do you have any preferences for colors you want to have in a cyclic colormap?

**Comment by horsto** [comment]
Great. Yes, I agree that cyclic colormaps are a bit niche, but on the other hand there is not a lot to choose from at the moment and I personally use them on a regular basis. There is `['twilight', 'twilight_shifted', 'hsv']` as standard in matplotlib.  `twilight` is quite dark and to me at least does not seem very usable. Seaborn lets you use `husl` https://seaborn.pydata.org/tutorial/color_palettes.html#using-circular-color-systems, but that stays in the "rainbow world". I think anything new there would be quite cool.

**Comment by 1313e** [comment]
Well, `hsv` is not a perceptually uniform sequential colormap and even `twilight` is not.
So, technically, matplotlib has no good cyclic colormaps.
I am personally not a fan of rainbows either, even if I have made some colormaps that resemble them.

I will have a look (hopefully during Christmas) if I can maybe convert `seasons` into a proper cyclic colormap.

**Comment by horsto** [comment]
That sounds good!

**Comment by 1313e** [comment]
So, as a bit of an update: I have been quite busy, but I also have been working on improving `viscm` to handle cyclic colormaps properly.
However, cyclic colormaps are incredibly tricky to create properly, due to them having 3 reference points instead of 2.

In case anyone is interested: When creating a diverging or cyclic colormap, the perceptual range of both sides of the colormap must be the same.
For a diverging colormap, this is not that hard, as you simply calculate the perceptual range of both sides and limit the side with the higher perceptual range to be the same as the lower one, thus not including the final few colors that you picked.
For a cyclic colormap on the other hand, you cannot do this, as both sides must not only start at the same point, but also end in the same (but different) point.
Therefore, to make both sides have the same perceptual range, you cannot simply remove a few colors/segments at the end of one side, but instead it is required to completely change the path that one end takes through colorspace to make sure it ends in the same point as the other end does.
Writing code that does this properly is quite tricky, so I am not sure when I will have figured it out.

**Comment by horsto** [comment]
That sounds very difficult indeed... I am sorry I am of no help. If you have something - even just something intermediary - it would be cool to discuss!

**Comment by 1313e** [comment]
I could do a dirty way of making one, but if I am going to add cyclic colormaps to CMasher, I want to do it properly.

**Comment by 1313e** [comment]
So, I got a bit bored today, so I decided to go and finally fix the issue of not being able to reliably produce cyclic colormaps.
After wasting way too many hours and paper on this, I think I finally found a solution that is reliable enough for the standards I have for CMasher.
So, support for cyclic colormaps was added in 1313e/viscm@921e96e.

As an example, here is a cyclic version of the `fusion` diverging colormap:
![new_cyclic](https://user-images.githubusercontent.com/30159027/112442195-b4f1e400-8d9f-11eb-9fa1-63a65d769936.png)


So, I guess I can make cyclic colormaps now.
Any preferences, @horsto?

**Comment by horsto** [comment]
Very cool - this is a great addition. 
Could you wrap `neon` or `tropical` into a circular map somehow? I.e. not to have the black and white zero / +- pi points?

**Comment by 1313e** [comment]
I could probably make a cyclic colormap that uses both of those colormaps.
I am also thinking of converting `seasons` (and maybe `pride`) to a cyclic colormap.

**Comment by 1313e** [comment]
I have added a cyclic version of `seasons` to CMasher now on the `dev` branch.
I will probably add at least 2 more cyclic colormaps before actually release v1.6.
So, stay tuned. :)

**Comment by 1313e** [comment]
@horsto How about something like this?
![infinity](https://user-images.githubusercontent.com/30159027/113080361-89994a00-9222-11eb-908f-b61141691e09.png)

**Comment by horsto** [comment]
Looks awesome. I think these are really cool additions to the repertoire. 

> I have added a cyclic version of seasons to CMasher now on the dev branch.
> I will probably add at least 2 more cyclic colormaps before actually releasing v1.6.
> So, stay tuned. :)

Fantastic...

**Comment by 1313e** [comment]
> Looks awesome. I think these are really cool additions to the repertoire.
> 
> > I have added a cyclic version of seasons to CMasher now on the dev branch.
> > I will probably add at least 2 more cyclic colormaps before actually releasing v1.6.
> > So, stay tuned. :)
> 
> Fantastic...

Yes, you are fine with that colormap being the cyclic version of `neon`/`tropical`?

**Comment by horsto** [comment]
Yes, I think it looks great and I don't have any ideas to improve it really. Is the saturation level for each color optimal? The only thing I'd think about is the 'punchiness' of the appearance, which could maybe be improved? Otherwise, great colormap - I would use it as is.

**Comment by 1313e** [comment]
I could increase the saturation, but then you lose lightness and perceptual range.

**Comment by horsto** [comment]
Got it. 

> This is what the colormap looks like when using its bright center.
Is that packaged / accessible through `_r` later?

**Comment by 1313e** [comment]
> Is that packaged / accessible through `_r` later?

One of them will be, yeah.

**Comment by 1313e** [comment]
Alright, 3 cyclic colormaps were added in v1.6.0.
Does this resolve this issue, @horsto?

**Comment by horsto** [comment]
Awesome work! Great addition... 
I will spread the word👍🏻

**Comment by 1313e** [comment]
PS: Don't forget to star the repo, so I can keep track of the number of users that CMasher has. :+1:
