### ISSUE TITLE
Colormap summary table

### ISSUE THREAD

**Issue by ycopin** [1313e/CMasher#32]
You mention in a documentation note that colormaps are sorted according to minimum and maximum lightness values, Starting (sequential) or central (diverging and cyclic) lightness value, Difference between the minimum and maximum lightness values and RMSE (root mean square error) of the derivative of the lightness profile. Could these quantities be centralized in a table?

**Comment by 1313e** [comment]
I could certainly make a table like that.
However, it will solely be for CMasher colormaps, for which the RMSE is pointless to report (it is always zero).
It will take me some time to write a script for it, as I would like to make that table in an automatic way, just like all colormap data is handled automatically in a script.
And, I have to figure out where I am going to put it in the online docs.

Do you have any suggestions?

**Comment by ycopin** [comment]
You could put it in place of the long list of links under "Individual colormaps" in https://cmasher.readthedocs.io/user/sequential.html

Running your quantitative script on historical matplotlib cmaps would also have an interest, e.g. for people to realize the gain to use cmasher...

**Comment by 1313e** [comment]
Uhm, that list is necessary to make the pages appear in the table of contents on the left.
In Sphinx, every page must be reachable from at least 1 other page without using the side bar.
However, I could put the table either right after the overview, or put it in the overview somehow.

**Comment by 1313e** [comment]
Question for you, @ycopin: Would you also want to have the lightness profile type for sequential colormaps be visible?

**Comment by 1313e** [comment]
So, for example, I can modify the colormap overviews to look like this:
![test](https://user-images.githubusercontent.com/30159027/113968530-9ba86780-9876-11eb-846b-b6aa55d75f63.png)

**Comment by 1313e** [comment]
Or this for all colormaps in MPL and CMasher.
![test](https://user-images.githubusercontent.com/30159027/113968940-694b3a00-9877-11eb-967a-0fb584944c88.png)

**Comment by ycopin** [comment]
Wow, that's a lot to ingest! Thanks for the hard work!

- can't links be included in tables?
- what is the definition of the triplet in the previous figures: I assume 1st two are somehow min and max of lightness, or start en end values? (it doesn't seem to work with all cmaps though, e.g. greys or season). What is the 3rd value, RMS of derivatives? In which units?
- I really like the individual lightness profiles in the "Full overview plot"!
- Maybe I missed it, but how do you actually define lightness and perceptual ranges? The triplet seems to refer to lightness, but not to perception? Is it at all related to Hue/Saturation/Brightness quantities? (sorry if I ask stupid questions...)
- Sorry, I don't understand the question "Would you also want to have the lightness profile type for sequential colormaps be visible?"...

**Comment by 1313e** [comment]
- They can, but I have a feeling you want to see the actual colormap when I am providing those values;
- The values under the names are the three values you mentioned: Starting or central lightness value; lightness range and lightness RMSE;
- The range is nothing more than the difference between the lowest and highest lightness/perceptual value;
The triplet indeed refers to the lightness, not to the perceptual profile.
The reason for that mostly is because the latter makes much less sense to the user than the former, while still telling a similar story.
The only time when they wouldn't tell a similar story is when you would randomly pick colors with proper lightness values.
As colormaps usually perform a track through colorspace, this does not happen very often.
But, theoretically speaking, the lightness profile alone does not tell the full picture.
- I also sort the sequential colormaps on their profile type first (as explained in the online docs) and was wondering if you wanted these to be visible as well. However, I personally think they don't provide any useful information to the user, so I won't actually include them.

**Comment by 1313e** [comment]
Any thoughts?

**Comment by 1313e** [comment]
I modified the 3 numbers to instead give starting/central lightness; final/outer lightness; and lightness RMSE values instead:
![test](https://user-images.githubusercontent.com/30159027/114344593-77fd5e00-9ba3-11eb-8b75-ba1900f7dfa6.png)

**Comment by ycopin** [comment]
> Any thoughts?

I was thinking about a way to define the "colorfulness" of a cmap: is there a standard metric to measure it? Obviously, a colorful cmap have a large extent in the viscm (a', b') plane, while a dull one will have a small imprint, and vanishing for pure B&W cmaps. Could one estimate colorfulness from projected area in the (a',b') plane?

**Comment by 1313e** [comment]
I could do so.
After all, in `viscm`, I have to calculate that as well.
Jist wondering how useful it would be to have that number.
It would basically be the perceptual range, as reported on the individual colormap pages in the overview plot.

**Comment by ycopin** [comment]
> It would basically be the perceptual range, as reported on the individual colormap pages in the overview plot.

Sorry to be a nuisance, but you repeatedly mention the "perceptual range", and I cannot seem to find any quantitative mention of it. The viscm shows the "perceptual derivative" in addition to "perceptual lightness deriv.", but I still don't understand how is defined perceptual range, or where to find the definition... :-/

**Comment by 1313e** [comment]
The perceptual range/derivative is a measure of the amount of color change there is in a colormap.
I can give you an exact definition of it if you want, but that just involves lots of math.
The just of it is that the higher the number, the more different colors a colormap goes through, and the more distinguishable neighbouring colors will be (assuming it is a perceptual uniform sequential colormap).

**Comment by 1313e** [comment]
@ycopin Do you have any further comments or suggestions?

**Comment by ycopin** [comment]
Nope, thanks!

**Comment by 1313e** [comment]
Alright, so I am thinking of replacing the RMSE of the lightness profile with the perceptual derivative instead, as that gives more insight into the number of colors that the colormap has.
After that, would you agree that replacing the sequential and diverging colormap overviews on the docs with an overview that has this information as well, solves your issue?

**Comment by ycopin** [comment]
I just provide semi-constructive comments, feel free to proceed as you think is best! And again, thanks for the hard work.

**Comment by 1313e** [comment]
So, this is what I was thinking of.
Of course, I will add an explanation of what the three numbers mean, but they give the starting/central lightness value; the final/outer lightness value; and the perceptual range of every colormap.
Basically, the first two numbers state what the range of lightness values is that the colormap covers.
The third value is a measure of how many colors there are in the colormap.
The lower the number, the less change in color there is between neighboring segments.

You can see this overview below.
I also am now sorting the colormaps within each group on the perceptual range, where you can see rather easily that the higher the value is, the more colors there are.
![test](https://user-images.githubusercontent.com/30159027/117116459-bf0cf680-add1-11eb-8c93-0c2130f0cda4.png)

Do you think these values themselves like this are helpful in picking a proper colormap?

**Comment by ycopin** [comment]
IMHO, 
* The 1st two numbers should be min and max, because the order is not really meaningful and a bit confusins (you can always take the reversed cmap)
* the 3rd number should somehow be normalized: strange to see "colorfulness = 100" for a grey cmap!
* Yes, I think this would be useful in tabular form, where one could order according to the various quantities.

**Comment by 1313e** [comment]
- The first two numbers are min and max lightness, for sequential colormaps that is.
Diverging and cyclic colormaps have no min and max, so I give the central and edge lightness values instead.
- The perceptual range has no maximum value, and therefore cannot be normalized. 
One could make a colormap that has a perceptual range below 100 but does have other colors than grey.
This would however require a lightness range that is less than 100.
- The docs are in RST, which cannot have any interactable tables in them.
So, it does not matter whether the values are in a table or in a plot.
