### ISSUE TITLE
Future incompatibility with MPL

### ISSUE THREAD

**Issue by neutrinoceros** [1313e/CMasher#43]
Just wanted to warn you about the pending deprecation of some functions in the `matplotlib.cm` namespace that are used in cmasher, like `get_cmap`

https://github.com/matplotlib/matplotlib/pull/23668

If it's any help, here's the patch I wrote to adapt to these deprecations in `yt`
https://github.com/yt-project/yt/pull/4089

I can also submit a PR here if you lack time for this.

**Comment by 1313e** [comment]
@neutrinoceros Thanks for the heads up.
I will make the changes for this soon.

**Comment by 1313e** [comment]
@neutrinoceros Well, I said I would do it soon, but it seems I cannot find the time to sit down and do this.
So, if you wish, you can open a PR with the required changes for it.

**Comment by blakeNaccarato** [comment]
I opened another PR against this issue to resolve `DeprecationWarnings` involving the use of `mplcm.get_cmap` and `mplcm.register_cmap`. I made the minimal necessary changes in code and tests. I left CMasher's mirror implementations for getting and registering colormaps untouched, and just changed the underlying calls to non-deprecated approaches.
