### ISSUE TITLE
Missing "*_s" colormaps

### ISSUE THREAD

**Issue by chadagreene** [1313e/CMasher#47]
The colormap overview image shows a few colormaps that end with _s (e.g., copper_s), but I don't see any corresponding text files for these. Is the repo missing something, or am _I_ missing something? 

[https://github.com/1313e/CMasher/blob/master/cmasher/colormaps/cmap_overview.png](https://github.com/1313e/CMasher/blob/master/cmasher/colormaps/cmap_overview.png)

**Comment by 1313e** [comment]
They are created automatically when importing the source file, as CMasher will detect that it is a cyclic colormap.
