### ISSUE TITLE
Is there a way to reverse the sequential cmasher colormaps?

### ISSUE THREAD

**Issue by lizwestbro** [1313e/CMasher#54]
Hello! 

I would like to reverse the cmasher colormap "neon" so that it changes from green to red rather than red to green. I did not see anything in the documentation that gives an easy way to do this with a colormap that does not come from matplotlib. Is this possible?

Thank you!

**Comment by thwit** [comment]
The reversed version of colormaps can be accessed by adding '_r' to the name:

`
import cmasher as cmr
cmap = cmr.neon
cmap_reversed = cmr.neon_r
`
